SRC = phonebook.cpp contact.cpp main.cpp utils_phonebook.cpp
HDRS = phonebook.hpp contact.hpp utils_phonebook.hpp
OBJ = $(SRC:.cpp=.o)
CC = g++
RM = rm -f
CPPFLAGS = -Wall -Wextra -Werror -std=c++98 -pedantic -g

NAME = worst_phonebook_ever

all: $(NAME)

%.o: %.cpp $(HDRS)
	$(CC) $(CPPFLAGS) -c $< -o $@

$(NAME): $(OBJ)
	$(CC) $(CPPFLAGS) $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean $(NAME)

.PHONY: all clean fclean re
